### Test call for quiz endpoint
GET http://localhost:8080/quiz
Accept: application/json

### Test call for quiz list endpoint
GET http://localhost:8080/quiz/all
Accept: application/json

### Test call for quiz list endpoint with filter
GET http://localhost:8080/quiz/all?title=Sample%20Quiz&description=sample&creationDateFrom=2023-01-01&creationDateTo=2023-12-31&category=SCIENCE&averageRatingFrom=4.0&averageRatingTo=5.0&pageIndex=0&pageSize=10&sortField=title&desc=false
Accept: application/json


### Test call for quiz by id endpoint
GET http://localhost:8080/quiz/37
Accept: application/json

### Test call for quiz by id endpoint
DELETE http://localhost:8080/question/10/delete
Accept: application/json


### Test call for filtered flagged content endpoint
GET http://localhost:8080/flagged-content/all
Accept: application/json